// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: test.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from test.proto</summary>
public static partial class TestReflection {

  #region Descriptor
  /// <summary>File descriptor for test.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static TestReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cgp0ZXN0LnByb3RvIoUBCgtQVFRyYW5zZm9ybRIRCglwb3NpdGlvblgYASAB",
          "KAISEQoJcG9zaXRpb25ZGAIgASgCEhEKCXBvc2l0aW9uWhgDIAEoAhIOCgZh",
          "bmdsZVgYBCABKAISDgoGYW5nbGVZGAUgASgCEg4KBmFuZ2xlWhgGIAEoAhIN",
          "CgVTcGVlZBgHIAEoAmIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PTTransform), global::PTTransform.Parser, new[]{ "PositionX", "PositionY", "PositionZ", "AngleX", "AngleY", "AngleZ", "Speed" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class PTTransform : pb::IMessage<PTTransform>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PTTransform> _parser = new pb::MessageParser<PTTransform>(() => new PTTransform());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PTTransform> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::TestReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PTTransform() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PTTransform(PTTransform other) : this() {
    positionX_ = other.positionX_;
    positionY_ = other.positionY_;
    positionZ_ = other.positionZ_;
    angleX_ = other.angleX_;
    angleY_ = other.angleY_;
    angleZ_ = other.angleZ_;
    speed_ = other.speed_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PTTransform Clone() {
    return new PTTransform(this);
  }

  /// <summary>Field number for the "positionX" field.</summary>
  public const int PositionXFieldNumber = 1;
  private float positionX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float PositionX {
    get { return positionX_; }
    set {
      positionX_ = value;
    }
  }

  /// <summary>Field number for the "positionY" field.</summary>
  public const int PositionYFieldNumber = 2;
  private float positionY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float PositionY {
    get { return positionY_; }
    set {
      positionY_ = value;
    }
  }

  /// <summary>Field number for the "positionZ" field.</summary>
  public const int PositionZFieldNumber = 3;
  private float positionZ_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float PositionZ {
    get { return positionZ_; }
    set {
      positionZ_ = value;
    }
  }

  /// <summary>Field number for the "angleX" field.</summary>
  public const int AngleXFieldNumber = 4;
  private float angleX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float AngleX {
    get { return angleX_; }
    set {
      angleX_ = value;
    }
  }

  /// <summary>Field number for the "angleY" field.</summary>
  public const int AngleYFieldNumber = 5;
  private float angleY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float AngleY {
    get { return angleY_; }
    set {
      angleY_ = value;
    }
  }

  /// <summary>Field number for the "angleZ" field.</summary>
  public const int AngleZFieldNumber = 6;
  private float angleZ_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float AngleZ {
    get { return angleZ_; }
    set {
      angleZ_ = value;
    }
  }

  /// <summary>Field number for the "Speed" field.</summary>
  public const int SpeedFieldNumber = 7;
  private float speed_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Speed {
    get { return speed_; }
    set {
      speed_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PTTransform);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PTTransform other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PositionX, other.PositionX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PositionY, other.PositionY)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PositionZ, other.PositionZ)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AngleX, other.AngleX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AngleY, other.AngleY)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AngleZ, other.AngleZ)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Speed, other.Speed)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (PositionX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PositionX);
    if (PositionY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PositionY);
    if (PositionZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PositionZ);
    if (AngleX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AngleX);
    if (AngleY != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AngleY);
    if (AngleZ != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AngleZ);
    if (Speed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Speed);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (PositionX != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(PositionX);
    }
    if (PositionY != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(PositionY);
    }
    if (PositionZ != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(PositionZ);
    }
    if (AngleX != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(AngleX);
    }
    if (AngleY != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(AngleY);
    }
    if (AngleZ != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(AngleZ);
    }
    if (Speed != 0F) {
      output.WriteRawTag(61);
      output.WriteFloat(Speed);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (PositionX != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(PositionX);
    }
    if (PositionY != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(PositionY);
    }
    if (PositionZ != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(PositionZ);
    }
    if (AngleX != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(AngleX);
    }
    if (AngleY != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(AngleY);
    }
    if (AngleZ != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(AngleZ);
    }
    if (Speed != 0F) {
      output.WriteRawTag(61);
      output.WriteFloat(Speed);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (PositionX != 0F) {
      size += 1 + 4;
    }
    if (PositionY != 0F) {
      size += 1 + 4;
    }
    if (PositionZ != 0F) {
      size += 1 + 4;
    }
    if (AngleX != 0F) {
      size += 1 + 4;
    }
    if (AngleY != 0F) {
      size += 1 + 4;
    }
    if (AngleZ != 0F) {
      size += 1 + 4;
    }
    if (Speed != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PTTransform other) {
    if (other == null) {
      return;
    }
    if (other.PositionX != 0F) {
      PositionX = other.PositionX;
    }
    if (other.PositionY != 0F) {
      PositionY = other.PositionY;
    }
    if (other.PositionZ != 0F) {
      PositionZ = other.PositionZ;
    }
    if (other.AngleX != 0F) {
      AngleX = other.AngleX;
    }
    if (other.AngleY != 0F) {
      AngleY = other.AngleY;
    }
    if (other.AngleZ != 0F) {
      AngleZ = other.AngleZ;
    }
    if (other.Speed != 0F) {
      Speed = other.Speed;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          PositionX = input.ReadFloat();
          break;
        }
        case 21: {
          PositionY = input.ReadFloat();
          break;
        }
        case 29: {
          PositionZ = input.ReadFloat();
          break;
        }
        case 37: {
          AngleX = input.ReadFloat();
          break;
        }
        case 45: {
          AngleY = input.ReadFloat();
          break;
        }
        case 53: {
          AngleZ = input.ReadFloat();
          break;
        }
        case 61: {
          Speed = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 13: {
          PositionX = input.ReadFloat();
          break;
        }
        case 21: {
          PositionY = input.ReadFloat();
          break;
        }
        case 29: {
          PositionZ = input.ReadFloat();
          break;
        }
        case 37: {
          AngleX = input.ReadFloat();
          break;
        }
        case 45: {
          AngleY = input.ReadFloat();
          break;
        }
        case 53: {
          AngleZ = input.ReadFloat();
          break;
        }
        case 61: {
          Speed = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
